###


GET http://127.0.0.1:3000


###


GET http://127.0.0.1:3000/post
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYjAyMWZjYmZhYmM0NjllZDk3ZTFjOCIsImlhdCI6MTY3MjQ4NzUyNCwiZXhwIjoxNjcyNDkxMTI0fQ.U9pxpunzd-bFpPnJ__VoqR62lE31A883pMxTAl7FTR0

###


GET http://127.0.0.1:3000/post?sender=12345


###


GET http://127.0.0.1:3000/post/637ea4655cf4944ece97a6d7



###


Post http://localhost:3000/post
Content-Type: application/json

{
    "message" : "this is my new message",
    "sender" : "12345"
}


###


POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "email" : "user1@gmail.com",
    "password" : "12345"
}

###


POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "email" : "user1@gmail.com",
    "password" : "12345"
}